In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(1000,50))
print(X)

[[ 13.02965222   4.73321577  12.47954643 ...  -5.12211289  -2.78422828
    8.26177187]
 [  6.13811892 -10.41226577 -18.31427617 ...  -2.4357277    0.18362207
    0.68895072]
 [  0.39618872  -6.25615223 -14.12506162 ...  10.39611214   4.53952367
  -12.20850534]
 ...
 [ 14.56086236   7.81855352   8.97629265 ... -21.47421667  14.48151793
    1.69888539]
 [ -8.69226274  11.17874634  20.72962256 ... -23.26208893  17.7548076
    2.28638599]
 [ 22.89817917  -4.48555416   3.634978   ... -21.4038702   14.40771991
   -6.85417426]]


In [3]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = (X - m) / std
print(X_norm)

[[ 1.13068966  0.37257276  1.13548506 ... -0.57622652 -0.35269644
   0.72881886]
 [ 0.44661614 -1.12590725 -1.87129452 ... -0.30906364 -0.05057144
  -0.01959427]
 [-0.12334446 -0.7147052  -1.46224999 ...  0.9670718   0.39285617
  -1.29423489]
 ...
 [ 1.28268201  0.67783324  0.79341932 ... -2.20245467  1.40494393
   0.08021641]
 [-1.02549043  1.01028763  1.94104145 ... -2.38025982  1.73816243
   0.13827841]
 [ 2.11026818 -0.53952386  0.27188108 ... -2.19545867  1.39743134
  -0.76507256]]


In [4]:
Z = np.array([[4, 5, 0],
              [1, 9, 3],
              [5, 1, 1],
              [3, 3, 3],
              [9, 9, 9],
              [4, 7, 1]])

In [5]:
print(np.nonzero(np.sum(Z, axis=1) > 10))

(array([1, 4, 5]),)


In [6]:
A, B = np.eye(3), np.eye(3)
print(A)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
AB = np.vstack((A, B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
